---
###############################################################################
#
#
- hosts: bifrost
  sudo: yes
  tasks:
    ############################################################################
    # APT Updates
    ############################################################################
    # Make sure our VM's software is ~@Latest
    - name: Apt Update
      apt: update_cache=yes
           upgrade=dist
           cache_valid_time=86400

    # Reboot if required.
    - name: Reboot system if required
      command: shutdown -r now 'Rebooting to complete system upgrade'
               removes=/var/run/reboot-required
      register: rebooted
    - name: Wait for VM Reboot.
      sudo: no
      local_action: wait_for
                    port=22
                    host="{{ip}}"
                    search_regex=OpenSSH
                    delay=10
                    timeout=900
      when: rebooted.changed

    - name: Ensure Google's Nameserver is used
      sudo: yes
      lineinfile: dest=/etc/resolv.conf line='nameserver 8.8.8.8'

    - name: Copy SSH public key into VM
      copy: src=~/.ssh/id_rsa.pub dest=~/.ssh/id_rsa.pub

    - name: Prepare VM for Bifrost
      command: /home/vagrant/bifrost/scripts/env-setup.sh

    - name: Install Bifrost
      shell: source /opt/stack/ansible/hacking/env-setup && ansible-playbook -vvvv -i inventory/localhost install.yaml
      args:
          chdir: /home/vagrant/bifrost/playbooks
          executable: /bin/bash

    - name: Enable AMT driver
      lineinfile: dest=/etc/ironic/ironic.conf line="enabled_drivers=agent_amttool, fake" regexp="^enabled_drivers=.*"
      sudo: yes

    - name: Fetch fix for AMT driver
      git: repo=https://github.com/devananda/ironic.git dest=/opt/stack/ironic version=new-amt-driver update=yes

    - name: Install updated Ironic service
      pip: name=/opt/stack/ironic state=latest

    - name: Restart ironic-conductor
      service: name=ironic-conductor state=restarted
