---
- name: "Initiate image build"
  shell: disk-image-create -a amd64 -o "{{http_boot_folder}}/{{deploy_image_filename}}" -t qcow2 vm ubuntu serial-console cloud-init-datasources "{{ extra_dib_elements}}"
  environment: dib_env_vars
