---
galaxy_info:
  author: Ironic Developers
  description: Create image with diskimage-builder for Bifrost
  company: OpenStack
  license: Apache
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - utopic
  categories:
  - cloud
  - cloud:openstack
dependencies: []
