# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Shade - Retrieving diskimage-builder from git.openstack.org"
  local_action: command git clone https://git.openstack.org/openstack/diskimage-builder chdir=/opt/stack creates=/opt/stack/diskimage-builder
- name: "Shade - Checking out master branch"
  local_action: command git checkout -f master chdir=/opt/stack/diskimage-builder
- name: "Shade - Resetting local repository"
  local_action: command git reset --hard master chdir=/opt/stack/diskimage-builder
- name: "Shade - Resyncing local repository"
  local_action: command git pull --ff-only chdir=/opt/stack/diskimage-builder
- name: "Shade - Installing patched library."
  local_action: command pip install -I --force-reinstall /opt/stack/diskimage-builder
