required_packages:
  - mysql-server
  - dnsmasq
  - rabbitmq-server
  - python-dev
  - python-pip
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt-dev
  - libssl-dev
  - libxml2-dev
  - ipxe
  - tftpd-hpa
  - tftp-hpa
  - syslinux-common
  - syslinux
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - genisoimage
  - kpartx
  - qemu-utils
  - python-openwsman
