# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Waiting for the base testvm machine to become available."
  wait_for: state=started port=22 host={{ item.split(',')[11] }} timeout=900
  with_lines:
    - cat {{ baremetal_csv_file }}
- name: "Pausing for 4 seconds to allow testvm to become fully operational and to avoid any potential sshd startup race."
  # NOTE(TheJulia): AFAIK sshd opens it's socket and then loads/generates
  # keys, which can become visible as a race, hence the four second pause.
  pause: seconds=4
- name: "Adding testvms to Ansible Inventory"
  add_host: name="{{ item.split(',')[11] }}:22" groups=testvm
  with_lines:
    - cat {{ baremetal_csv_file }}
- name: "Removing testvm hosts from ssh known_hosts file."
  command: ssh-keygen -R "{{ item.split(',')[11] }}"
  with_lines:
    - cat {{ baremetal_csv_file }}
- name: "Adding testvm hosts from ssh known_hosts file."
  shell: ssh-keyscan "{{ item.split(',')[11] }}" >> "{{ ansible_env.HOME }}/.ssh/known_hosts"
  with_lines:
    - cat {{ baremetal_csv_file }}
