---
- hosts: localhost
  name: "Install Ironic on the local host."
  connection: local
  sudo: yes
  gather_facts: yes
  roles:
    - { role: bifrost-prep-for-install, when: skip_install is not defined }
    - ironic-install
