---
required_packages_ubuntu:
  - mysql-server
  - dnsmasq
  - rabbitmq-server
  - python-dev
  - python-pip
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt-dev
  - libssl-dev
  - libxml2-dev
  - ipxe
  - tftpd-hpa
  - tftp-hpa
  - syslinux-common
  - syslinux
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - genisoimage
  - qemu-utils
  - kpartx
http_boot_folder: /httpboot
transform_boot_image: false
ironic_url: "http://localhost:6385/"
network_interface: "eth0"
ssh_public_key_path: ~/.ssh/id_rsa.pub
