---
required_packages_ubuntu:
  - mysql-server
  - dnsmasq
  - rabbitmq-server
  - python-dev
  - python-pip
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt-dev
  - libssl-dev
  - libxml2-dev
  - ipxe
  - tftpd-hpa
  - tftp-hpa
  - syslinux-common
  - syslinux
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - genisoimage
  - kpartx
http_boot_folder: /httpboot
transform_boot_image: false
ironic_url: "http://localhost:6385/"
ssh_public_key_path: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
dib_env_vars:
  DIB_CLOUD_INIT_DATASOURCES: "ConfigDrive"
# extra_dib_elements is a space separated list of elements.
extra_dib_elements: ""
create_image_via_dib: true
transform_boot_image: false
